name: integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  e2e-upload:
    uses: ./.github/workflows/_compose-stack.yml
    with:
      script-path: ./scripts/e2e_upload.sh
      service-set: minimal
