name: integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  e2e-upload:
    uses: dgaspard/muse/.github/workflows/_compose-stack.yml@fix/story-derivation-workflow
    with:
      script-path: ./scripts/e2e_upload.sh
      service-set: minimal
